In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/mohali_weather_2016_2025.csv", skiprows=2)

In [5]:
df.head()

,time,weather_code (wmo code),temperature_2m_mean (°C),temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),wind_speed_10m_max (km/h),relative_humidity_2m_mean (%)
0,2016-01-01,3,13.8,21.4,9.5,0.0,8.0,62
1,2016-01-02,3,13.3,21.5,7.5,0.0,12.2,65
2,2016-01-03,2,13.4,22.0,8.1,0.0,16.7,69
3,2016-01-04,3,13.6,19.1,8.5,0.0,6.4,74
4,2016-01-05,3,16.3,24.0,11.7,0.0,9.8,66

In [7]:
df.shape

(3653, 8)

In [8]:
df.dtypes

time                              object
weather_code (wmo code)            int64
temperature_2m_mean (°C)         float64
temperature_2m_max (°C)          float64
temperature_2m_min (°C)          float64
precipitation_sum (mm)           float64
wind_speed_10m_max (km/h)        float64
relative_humidity_2m_mean (%)      int64
dtype: object

In [9]:
df["time"] = pd.to_datetime(df["time"])

In [10]:
df.dtypes

time                             datetime64[ns]
weather_code (wmo code)                   int64
temperature_2m_mean (°C)                float64
temperature_2m_max (°C)                 float64
temperature_2m_min (°C)                 float64
precipitation_sum (mm)                  float64
wind_speed_10m_max (km/h)               float64
relative_humidity_2m_mean (%)             int64
dtype: object

In [11]:
df.isna().sum()

time                             0
weather_code (wmo code)          0
temperature_2m_mean (°C)         0
temperature_2m_max (°C)          0
temperature_2m_min (°C)          0
precipitation_sum (mm)           0
wind_speed_10m_max (km/h)        0
relative_humidity_2m_mean (%)    0
dtype: int64

In [12]:
df["time"].duplicated().sum()

np.int64(0)

In [14]:
df.describe()

,time,weather_code (wmo code),temperature_2m_mean (°C),temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),wind_speed_10m_max (km/h),relative_humidity_2m_mean (%)
count,3653,3653.000000,3653.000000,3653.000000,3653.000000,3653.000000,3653.000000,3653.000000
mean,2020-12-31 00:00:00,24.205311,24.496469,30.378128,19.731618,2.017438,13.465508,64.858472
min,2016-01-01 00:00:00,0.000000,8.600000,11.900000,4.400000,0.000000,4.500000,18.000000
25%,2018-07-02 00:00:00,1.000000,18.000000,25.300000,13.000000,0.000000,9.800000,53.000000
50%,2020-12-31 00:00:00,3.000000,26.800000,31.900000,21.000000,0.000000,12.800000,69.000000
75%,2023-07-02 00:00:00,51.000000,30.200000,35.000000,26.500000,1.000000,16.300000,78.000000
max,2025-12-31 00:00:00,65.000000,39.100000,45.800000,32.800000,162.500000,43.600000,96.000000
std,NaN,26.649114,7.089293,6.853298,7.168158,7.685054,4.625390,16.782856

In [15]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
time,3653,2020-12-31 00:00:00,2016-01-01 00:00:00,2018-07-02 00:00:00,2020-12-31 00:00:00,2023-07-02 00:00:00,2025-12-31 00:00:00,NaN
weather_code (wmo code),3653.0,24.205311,0.0,1.0,3.0,51.0,65.0,26.649114
temperature_2m_mean (°C),3653.0,24.496469,8.6,18.0,26.8,30.2,39.1,7.089293
temperature_2m_max (°C),3653.0,30.378128,11.9,25.3,31.9,35.0,45.8,6.853298
temperature_2m_min (°C),3653.0,19.731618,4.4,13.0,21.0,26.5,32.8,7.168158
precipitation_sum (mm),3653.0,2.017438,0.0,0.0,0.0,1.0,162.5,7.685054
wind_speed_10m_max (km/h),3653.0,13.465508,4.5,9.8,12.8,16.3,43.6,4.62539
relative_humidity_2m_mean (%),3653.0,64.858472,18.0,53.0,69.0,78.0,96.0,16.782856

In [16]:
expected_days = pd.date_range(start="2016-01-01", end="2025-12-31")

len(expected_days), len(df)

(3653, 3653)

In [17]:
df["time"].diff().value_counts()

time
1 days    3652
Name: count, dtype: int64

In [18]:
df = df.rename(columns={
    "time": "date",
    "weather_code (wmo code)": "weather_code",
    "temperature_2m_mean (°C)": "temp_mean",
    "temperature_2m_max (°C)": "temp_max",
    "temperature_2m_min (°C)": "temp_min",
    "precipitation_sum (mm)": "rainfall",
    "wind_speed_10m_max (km/h)": "wind_speed",
    "relative_humidity_2m_mean (%)": "humidity"
})

In [19]:
df.head()

,date,weather_code,temp_mean,temp_max,temp_min,rainfall,wind_speed,humidity
0,2016-01-01,3,13.8,21.4,9.5,0.0,8.0,62
1,2016-01-02,3,13.3,21.5,7.5,0.0,12.2,65
2,2016-01-03,2,13.4,22.0,8.1,0.0,16.7,69
3,2016-01-04,3,13.6,19.1,8.5,0.0,6.4,74
4,2016-01-05,3,16.3,24.0,11.7,0.0,9.8,66

In [20]:
df = df.sort_values("date").reset_index(drop=True)

In [21]:
df[["date", "temp_mean", "rainfall"]].head()

        date  temp_mean  rainfall
0 2016-01-01       13.8       0.0
1 2016-01-02       13.3       0.0
2 2016-01-03       13.4       0.0
3 2016-01-04       13.6       0.0
4 2016-01-05       16.3       0.0